import pandas as pd
import matplotlib.pyplot as plt
import os
import argparse
import glob

def visualize_memory_logs(log_paths, save_path=None):
    """
    주어진 경로에서 메모리 로그 CSV 파일들을 찾아 시각화합니다.

    Args:
        log_paths (list): 로그 파일 또는 디렉터리 경로의 리스트.
        save_path (str, optional): 그래프를 이미지 파일로 저장할 경로. Defaults to None.
    """
    all_files = []
    for path in log_paths:
        if os.path.isdir(path):
            # 디렉터리면 내부의 모든 .csv 파일을 찾습니다.
            all_files.extend(glob.glob(os.path.join(path, '*.csv')))
        elif os.path.isfile(path) and path.endswith('.csv'):
            # 파일이면 리스트에 직접 추가합니다.
            all_files.append(path)
        else:
            print(f"Warning: '{path}' is not a valid file or directory. Skipping.")

    if not all_files:
        print("Error: No CSV log files found in the specified paths.")
        return

    plt.style.use('seaborn-v0_8-whitegrid')
    fig, ax = plt.subplots(figsize=(14, 8))

    print("\nPlotting files:")
    for filepath in sorted(all_files):
        try:
            df = pd.read_csv(filepath)

            # 파일 이름에서 의미 있는 레이블 추출
            # 예: mem_baseline_34_3_8_28-32_20240128163000.csv -> baseline_34_3_8_28-32
            filename = os.path.basename(filepath)
            label_parts = filename.replace('mem_', '').replace('.csv', '').split('_')
            if len(label_parts) > 1 and label_parts[-1].isdigit() and len(label_parts[-1]) > 8:
                label = '_'.join(label_parts[:-1]) # 마지막 타임스탬프 부분 제거
            else:
                label = '_'.join(label_parts)

            print(f" - '{label}' from {filename}")

            # 시간(초)을 x축, 메모리(MB)를 y축으로 설정하여 그래프 그리기
            ax.plot(df['Elapsed_Time_sec'], df['Memory_Usage_MB'], marker='o', linestyle='-', label=label)

        except Exception as e:
            print(f"Error processing file {filepath}: {e}")

    ax.set_title('Memory Usage Comparison Over Time', fontsize=16)
    ax.set_xlabel('Elapsed Time (seconds)', fontsize=12)
    ax.set_ylabel('Memory Usage (MB)', fontsize=12)
    ax.legend(title="Experiment", bbox_to_anchor=(1.02, 1), loc='upper left')
    ax.grid(True, which='both', linestyle='--', linewidth=0.5)

    plt.tight_layout(rect=[0, 0, 0.85, 1]) # 범례가 잘리지 않도록 레이아웃 조정

    if save_path:
        plt.savefig(save_path, dpi=300)
        print(f"\nGraph saved to '{save_path}'")
    else:
        plt.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Visualize memory usage from log files generated by the classification experiments.")
    parser.add_argument('log_paths', nargs='+', help='One or more paths to log directories or specific CSV files.')
    parser.add_argument('--save', type=str, default=None, help='Path to save the plot image file (e.g., "memory_plot.png"). If not provided, shows the plot interactively.')

    args = parser.parse_args()

    visualize_memory_logs(args.log_paths, args.save)